version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: python main.py
    depends_on:
      - loki
      - promtail  # Ensure Promtail starts before your app

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /path/to/logs:/var/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki  # Ensure Loki is available before Promtail starts


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI port
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
